# Generated by Django 6.0.1 on 2026-01-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='comprado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('BASICO', 'Básico (Siempre hay)'), ('OCASIONAL', 'Ocasional (Desodorante, Talcos, etc.)')], default='BASICO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_casa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.CharField(default='1 unidad', max_length=50),
        ),
    ]
