# Generated by Django 6.0.1 on 2026-01-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
